# Generated by Django 5.2.3 on 2025-06-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcmcertificate',
            name='certificate_json',
            field=models.BinaryField(),
        ),
    ]
