# Generated by Django 5.2.3 on 2025-06-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_fcmcertificate_certificate_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fcmcertificate',
            name='certificate_json',
        ),
        migrations.AddField(
            model_name='fcmcertificate',
            name='certificate_file',
            field=models.FileField(null=True, upload_to='fcm_certificates/'),
        ),
    ]
