# Generated by Django 5.2.3 on 2025-06-23 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_fcmcertificate_certificate_json_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fcmcertificate',
            old_name='certificate_file',
            new_name='certificate_json',
        ),
    ]
