# Generated by Django 5.2.3 on 2025-06-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_certificate_file_fcmcertificate_certificate_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcmcertificate',
            name='certificate_json',
            field=models.JSONField(),
        ),
    ]
