# Generated by Django 4.2.7 on 2025-08-18 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_messaging', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FCMLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernames', models.TextField()),
                ('tokens', models.TextField()),
                ('message_title', models.CharField(max_length=200, null=True)),
                ('message_body', models.CharField(max_length=1024)),
                ('success_count', models.IntegerField()),
                ('failure_count', models.IntegerField()),
                ('responses', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=255)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('uuid', models.CharField(max_length=255, null=True)),
                ('platform', models.CharField(max_length=255, null=True)),
                ('is_dashbaord_login', models.BooleanField(default=False, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this device active and able to receive notifications?')),
                ('os_version', models.CharField(max_length=255, null=True)),
                ('device_model', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Device',
                'verbose_name_plural': 'User Devices',
                'unique_together': {('username', 'uuid')},
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='fcmcertificate',
            name='name',
        ),
    ]
