# Generated by Django 4.2.7 on 2025-08-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_messaging', '0002_fcmlog_userdevice_delete_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcmcertificate',
            name='firebase_config',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fcmcertificate',
            name='vapid_key',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdevice',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
