# Generated by Django 4.2.7 on 2025-08-21 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_messaging', '0003_fcmcertificate_firebase_config_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdevice',
            old_name='is_dashbaord_login',
            new_name='is_dashboard_login',
        ),
    ]
